services:
  db:
    image: postgres:alpine

    environment:
      POSTGRES_PASSWORD: 1234567
      POSTGRES_USER: root
      POSTGRES_DB: db
      PGDATA: /var/lib/postgresql/data/pgdata

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    
  redis:
    image: redis:alpine

    ports:
      - "6379:6379"

    volumes:
      - redisdata:/data

  s3:
    image: rustfs/rustfs:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - rustfs-data:/data
    environment:
      RUSTFS_ACCESS_KEY: root
      RUSTFS_SECRET_KEY: 12345678

volumes:
  redisdata:
  rustfs-data:
  pgdata: