"""empty message

Revision ID: 8cc7ccef8351
Revises:
Create Date: 2026-09-25 17:16:35.413412

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "8cc7ccef8351"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
